### ISSUE TITLE
请问支持Ionic 3吗？IOS和Android都支持吗？

### ISSUE THREAD

**Issue by dythbj** [vivlong/cordova-plugin-vivlong-aliyunpush#1]
请问支持Ionic 3吗？IOS和Android都支持吗？

**Comment by vivlong** [comment]
支持Ionic 3，目前只支持Android，且配置文件例如 aliyun-emas-services.json 需要自行添加，Ionic3中调用需自行封装一下

**Comment by dythbj** [comment]
> 支持Ionic 3，目前只支持Android，且配置文件例如 aliyun-emas-services.json 需要自行添加，Ionic3中调用需自行封装一下

有支持IOS的计划吗？

**Comment by dythbj** [comment]
或者我们自己如何修改能支持IOS？另外华为、小米等第三方通道的推送的稳定性如何？

**Comment by dythbj** [comment]
[https://github.com/llwwbb/cordova-plugin-AliPush](url)这个库你研究过吗？

**Comment by dythbj** [comment]
刚刚准备用阿里的推送，正在找接入IONIC的办法，谢谢

**Comment by vivlong** [comment]
这个插件目前是内部产品在商用，IOS的代码可以先自行添加，后续会完善IOS端，目前都有接入第三方通道

**Comment by dythbj** [comment]
请问aliyun-emas-services.json需要在哪配置？Ionic3中调用需自行封装一下，能具体说说吗？

**Comment by vivlong** [comment]
aliyun-emas-services.json下载后复制到 platform\app\ 目录即可
这个插件的ionic-native还没完善，可以自己写一个：eg
`declare var AliyunPush: any;

export class AliyunPushPlugin {
public static getDeviceId() {
		return new Promise((resolve, reject) => {
			AliyunPush.getDeviceId(
				result => {
					resolve(result);
				},
				error => {
					reject(error);
				}
			);
		});
	}
}`

**Comment by dythbj** [comment]
> aliyun-emas-services.json下载后复制到 platform\app\ 目录即可
> 这个插件的ionic-native还没完善，可以自己写一个：eg
> `declare var AliyunPush: any;
> 
> export class AliyunPushPlugin {
> public static getDeviceId() {
> return new Promise((resolve, reject) => {
> AliyunPush.getDeviceId(
> result => {
> resolve(result);
> },
> error => {
> reject(error);
> }
> );
> });
> }
> }`

![image](https://user-images.githubusercontent.com/41282663/72245602-e7e10980-362b-11ea-8958-ab651528098c.png)
platform下新建一个app目录？

**Comment by vivlong** [comment]
platforms\android\app\

**Comment by dythbj** [comment]
> platforms\android\app\

platforms\android\下好像也没有app这个目录呃

**Comment by vivlong** [comment]
cordova-android 7.0.0 以上 修改了 Android 项目结构 有APP

**Comment by dythbj** [comment]
> cordova-android 7.0.0 以上 修改了 Android 项目结构 有APP

您有没有具体一点的文章整体介绍如何使用这个包的（博客啥的）？

**Comment by dythbj** [comment]
或者方便微信加您一下吗？

**Comment by vivlong** [comment]
或者您可以先使用 https://github.com/llwwbb/cordova-plugin-AliPush或其他几个库
这个插件目前还在迭代中，没有完善的文档

**Comment by dythbj** [comment]
> 或者您可以先使用 [https://github.com/llwwbb/cordova-plugin-AliPush或其他几个库](https://github.com/llwwbb/cordova-plugin-AliPush%E6%88%96%E5%85%B6%E4%BB%96%E5%87%A0%E4%B8%AA%E5%BA%93)
> 这个插件目前还在迭代中，没有完善的文档

那个库我看好久没更新了，估计alipush的SDK估计早就过期了，而且好像没有集成华为、小米这些渠道。。。

**Comment by vivlong** [comment]
您可以用 https://github.com/Garic-z/cordova-plugin-yaAliyunPush 这个，实测可用

**Comment by dythbj** [comment]
收到，感谢
