### ISSUE TITLE
请教js调用问题

### ISSUE THREAD

**Issue by okings** [vivlong/cordova-plugin-vivlong-aliyunpush#3]
先赞一个，找了一圈终于找到最新的版本了。请问下插件安装完成后，html页面的js如何调用？比如其他插件都有类似代码：
```
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    xxxxxx.registerPush('Account',function(s){
        console.log(JSON.stringify(s));
    },function(e){
        console.log(JSON.stringify(e));
    })
    xxxxxx.on("register", function (data) {
        console.log("register:", JSON.stringify(data));
    });
    xxxxxx.on("click", function (data) {
        console.log("click:" + JSON.stringify(data));
    });
}
```

**Comment by vivlong** [comment]
参考README中Ionic3示例，新建一个class，然后再引用即可

declare var AliyunPush: any;

  export class AliyunPushPlugin {

    public static getDeviceId() {
      return new Promise((resolve, reject) => {
        AliyunPush.getDeviceId(
          result => {
            resolve(result);
          },
          error => {
            reject(error);
          }
        );
      });
    }

  }

**Comment by okings** [comment]
V，试了下，这段代码是Ioic3，如果我只是cordova引用，上面代码js报错的，能详细点么，初学...

**Comment by vivlong** [comment]
cordova 引用同理，比如

declare var AliyunPush: any;
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    AliyunPush.getDeviceId(function(s){
        console.log(JSON.stringify(s));
    },function(e){
        console.log(JSON.stringify(e));
    });
}

**Comment by okings** [comment]
谢谢！ declare var AliyunPush: any; 这句呢？js不认

**Comment by okings** [comment]
所以是怎么识别这个 AliyunPush 变量的？

**Comment by vivlong** [comment]
deviceready里 你试一下 window.AliyunPush

**Comment by okings** [comment]
好的，非常感谢！
